## HellHard (Main-Config) ##
# Debug pokazuje dodatkowe informacje do konsoli. Lepiej wylaczyc. :P
debug: true
# Uzupelnij ponizsze menu danymi.
storage-config:
  # W jakiej formie maja byc zapisywane dane o graczu?
  # Dostepne zapisy: (FLAT, MYSQL, MONGO, H2)
  storage-type: FLAT
  # Jaki prefix ustawic dla danych?
  # Dla FLAT prefix nie jest uzywany.
  prefix: hellhard
  # FLAT   : nie jest wymagane podawanie dodatkowych informacji
  # MONGO  : mongodb://{host}:{port}/?maxPoolSize=20&w=majority
  # MYSQL  : jdbc:mysql://{host}:{port}/{database}?user={username}&password={password}
  # H2     : jdbc:h2:file:./plugins/{data_folder}/storage;mode=mysql
  uri: ''
# verify role ids
role-ids:
- '1157576832397348978'
- '1157576832397348979'
# proposition channel id
proposition-channel-id: '1157576833525620785'
blocked-words:
- '@everyone'
- '@here'
# welcome channel id
welcome-channel-id: '1157576833215254540'
# ticket category
ticket-category-id: '1163070567365234728'
