## StormCity (Main-Config) ##
# Debug pokazuje dodatkowe informacje do konsoli. Lepiej wylaczyc. :P
debug: true
# Uzupelnij ponizsze menu danymi.
storage-config:
  # W jakiej formie maja byc zapisywane dane o graczu?
  # Dostepne zapisy: (FLAT, MYSQL, MONGO, H2)
  storage-type: FLAT
  # Jaki prefix ustawic dla danych?
  # Dla FLAT prefix nie jest uzywany.
  prefix: stormcity
  # FLAT   : nie jest wymagane podawanie dodatkowych informacji
  # MONGO  : mongodb://{host}:{port}/?maxPoolSize=20&w=majority
  # MYSQL  : jdbc:mysql://{host}:{port}/{database}?user={username}&password={password}
  # H2     : jdbc:h2:file:./plugins/{data_folder}/storage;mode=mysql
  uri: ''
# verify role id
role-id: '1028656959148261437'
blocked-words:
- '@everyone'
- '@here'
# welcome channel id
welcome-channel-id: '1028660386209218641'
# ticket category
ticket-category-id: '1063542120406847621'
